#############################################################################
# Makefile for building: planet
# Generated by qmake (2.01a) (Qt 4.5.2) on: jeu. avr. 8 03:37:25 2010
# Project:  planet.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile planet.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = astre.cpp \
		astrefield.cpp \
		gameboard.cpp \
		main.cpp \
		widproperties.cpp moc_astrefield.cpp \
		moc_gameboard.cpp \
		moc_widproperties.cpp
OBJECTS       = astre.o \
		astrefield.o \
		gameboard.o \
		main.o \
		widproperties.o \
		moc_astrefield.o \
		moc_gameboard.o \
		moc_widproperties.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		planet.pro
QMAKE_TARGET  = planet
DESTDIR       = 
TARGET        = planet

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: planet.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile planet.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile planet.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/planet1.0.0 || $(MKDIR) .tmp/planet1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/planet1.0.0/ && $(COPY_FILE) --parents astre.h astrefield.h gameboard.h widproperties.h .tmp/planet1.0.0/ && $(COPY_FILE) --parents astre.cpp astrefield.cpp gameboard.cpp main.cpp widproperties.cpp .tmp/planet1.0.0/ && (cd `dirname .tmp/planet1.0.0` && $(TAR) planet1.0.0.tar planet1.0.0 && $(COMPRESS) planet1.0.0.tar) && $(MOVE) `dirname .tmp/planet1.0.0`/planet1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/planet1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_astrefield.cpp moc_gameboard.cpp moc_widproperties.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_astrefield.cpp moc_gameboard.cpp moc_widproperties.cpp
moc_astrefield.cpp: astre.h \
		astrefield.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) astrefield.h -o moc_astrefield.cpp

moc_gameboard.cpp: gameboard.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gameboard.h -o moc_gameboard.cpp

moc_widproperties.cpp: astre.h \
		widproperties.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widproperties.h -o moc_widproperties.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

astre.o: astre.cpp astre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o astre.o astre.cpp

astrefield.o: astrefield.cpp astre.h \
		astrefield.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o astrefield.o astrefield.cpp

gameboard.o: gameboard.cpp astrefield.h \
		astre.h \
		gameboard.h \
		widproperties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameboard.o gameboard.cpp

main.o: main.cpp gameboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widproperties.o: widproperties.cpp widproperties.h \
		astre.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widproperties.o widproperties.cpp

moc_astrefield.o: moc_astrefield.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_astrefield.o moc_astrefield.cpp

moc_gameboard.o: moc_gameboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gameboard.o moc_gameboard.cpp

moc_widproperties.o: moc_widproperties.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widproperties.o moc_widproperties.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

