######################################################################
# Automatically generated by qmake (3.0) Di. Dez. 8 13:44:50 2015
######################################################################

TEMPLATE = app
TARGET = planet
INCLUDEPATH += .

# Input
HEADERS += astre.h astrefield.h gameboard.h widproperties.h
SOURCES += astre.cpp astrefield.cpp gameboard.cpp main.cpp widproperties.cpp

QT += widgets
