######################################################################
# Automatically generated by qmake (2.01a) lun. mars 29 04:37:18 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += qt debug

# Input
HEADERS += astre.h astrefield.h gameboard.h widproperties.h
SOURCES += astre.cpp astrefield.cpp gameboard.cpp main.cpp widproperties.cpp
